services:
  tf-mysql:
    image: mysql:8.0
    container_name: tf-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - "${MYSQL_PORT}:3306"
    expose:
      - "3306"
    volumes:
      - tf-mysql_data:/var/lib/mysql:rw
      - ./initdb:/docker-entrypoint-initdb.d:ro
      - ${CSV_DIR}:/csv
      - /etc/localtime:/etc/localtime:ro
    command: --default-authentication-plugin=mysql_native_password --local-infile=1 --secure-file-priv=/csv

  tf-phpmyadmin:
    image: phpmyadmin:latest
    container_name: tf-phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=tf-mysql
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${PMA_PORT}:80"
    expose:
      - "80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - tf-mysql

  tf-metabase:
    build:
      context: .
      dockerfile: Dockerfile
    image: metabase-duckdb:latest
    container_name: tf-metabase
    restart: unless-stopped
    environment:
      - MB_PLUGINS_DIR=${MB_PLUGINS_DIR:-/plugins}
      - MB_DB_TYPE=mysql
      - MB_DB_DBNAME=${MB_DB_DBNAME:-metabase}
      - MB_DB_PORT=3306
      - MB_DB_USER=${MYSQL_USER}
      - MB_DB_PASS=${MYSQL_PASSWORD}
      - MB_DB_HOST=tf-mysql
    ports:
      - "${MB_PORT}:3000"
    expose:
      - "3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - tf-mysql

volumes:
  tf-mysql_data:
    name: tf-mysql_data
